//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ItemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endAuctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[][] imgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.ItemService.Order[] ordersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] rowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startAuctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockRemainedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endAuction {
            get {
                return this.endAuctionField;
            }
            set {
                if ((this.endAuctionField.Equals(value) != true)) {
                    this.endAuctionField = value;
                    this.RaisePropertyChanged("endAuction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] img {
            get {
                return this.imgField;
            }
            set {
                if ((object.ReferenceEquals(this.imgField, value) != true)) {
                    this.imgField = value;
                    this.RaisePropertyChanged("img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.ItemService.Order[] orders {
            get {
                return this.ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.ordersField, value) != true)) {
                    this.ordersField = value;
                    this.RaisePropertyChanged("orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] rowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.rowVersionField, value) != true)) {
                    this.rowVersionField = value;
                    this.RaisePropertyChanged("rowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startAuction {
            get {
                return this.startAuctionField;
            }
            set {
                if ((this.startAuctionField.Equals(value) != true)) {
                    this.startAuctionField = value;
                    this.RaisePropertyChanged("startAuction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stockRemained {
            get {
                return this.stockRemainedField;
            }
            set {
                if ((this.stockRemainedField.Equals(value) != true)) {
                    this.stockRemainedField = value;
                    this.RaisePropertyChanged("stockRemained");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime buyDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.ItemService.Person buyerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime buyDay {
            get {
                return this.buyDayField;
            }
            set {
                if ((this.buyDayField.Equals(value) != true)) {
                    this.buyDayField = value;
                    this.RaisePropertyChanged("buyDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.ItemService.Person buyer {
            get {
                return this.buyerField;
            }
            set {
                if ((object.ReferenceEquals(this.buyerField, value) != true)) {
                    this.buyerField = value;
                    this.RaisePropertyChanged("buyer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                if ((this.totalPriceField.Equals(value) != true)) {
                    this.totalPriceField = value;
                    this.RaisePropertyChanged("totalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.ItemService.Company companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.ItemService.Item[] itemsBoughtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.ItemService.Item[] itemsSoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.ItemService.Company company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.ItemService.Item[] itemsBought {
            get {
                return this.itemsBoughtField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsBoughtField, value) != true)) {
                    this.itemsBoughtField = value;
                    this.RaisePropertyChanged("itemsBought");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.ItemService.Item[] itemsSold {
            get {
                return this.itemsSoldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsSoldField, value) != true)) {
                    this.itemsSoldField = value;
                    this.RaisePropertyChanged("itemsSold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                if ((this.zipCodeField.Equals(value) != true)) {
                    this.zipCodeField = value;
                    this.RaisePropertyChanged("zipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class ItemFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItemService.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItem", ReplyAction="http://tempuri.org/IItemService/getItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/getItemItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.getItemResponse getItem(WebClient.ItemService.getItemRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItem", ReplyAction="http://tempuri.org/IItemService/getItemResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.getItemResponse> getItemAsync(WebClient.ItemService.getItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/setItem", ReplyAction="http://tempuri.org/IItemService/setItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/setItemItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.setItemResponse setItem(WebClient.ItemService.setItemRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/setItem", ReplyAction="http://tempuri.org/IItemService/setItemResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.setItemResponse> setItemAsync(WebClient.ItemService.setItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/itemsSold", ReplyAction="http://tempuri.org/IItemService/itemsSoldResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/itemsSoldItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.itemsSoldResponse itemsSold(WebClient.ItemService.itemsSoldRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/itemsSold", ReplyAction="http://tempuri.org/IItemService/itemsSoldResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.itemsSoldResponse> itemsSoldAsync(WebClient.ItemService.itemsSoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItemsCategory", ReplyAction="http://tempuri.org/IItemService/getItemsCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/getItemsCategoryItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.getItemsCategoryResponse getItemsCategory(WebClient.ItemService.getItemsCategoryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItemsCategory", ReplyAction="http://tempuri.org/IItemService/getItemsCategoryResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.getItemsCategoryResponse> getItemsCategoryAsync(WebClient.ItemService.getItemsCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItemsCart", ReplyAction="http://tempuri.org/IItemService/getItemsCartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/getItemsCartItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.getItemsCartResponse getItemsCart(WebClient.ItemService.getItemsCartRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getItemsCart", ReplyAction="http://tempuri.org/IItemService/getItemsCartResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.getItemsCartResponse> getItemsCartAsync(WebClient.ItemService.getItemsCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getOrders", ReplyAction="http://tempuri.org/IItemService/getOrdersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/getOrdersItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.getOrdersResponse getOrders(WebClient.ItemService.getOrdersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/getOrders", ReplyAction="http://tempuri.org/IItemService/getOrdersResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.getOrdersResponse> getOrdersAsync(WebClient.ItemService.getOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/setOrder", ReplyAction="http://tempuri.org/IItemService/setOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/setOrderItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.setOrderResponse setOrder(WebClient.ItemService.setOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/setOrder", ReplyAction="http://tempuri.org/IItemService/setOrderResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.setOrderResponse> setOrderAsync(WebClient.ItemService.setOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/bought", ReplyAction="http://tempuri.org/IItemService/boughtResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/boughtItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.boughtResponse bought(WebClient.ItemService.boughtRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/bought", ReplyAction="http://tempuri.org/IItemService/boughtResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.boughtResponse> boughtAsync(WebClient.ItemService.boughtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/latestAdded", ReplyAction="http://tempuri.org/IItemService/latestAddedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClient.ItemService.ItemFault), Action="http://tempuri.org/IItemService/latestAddedItemFaultFault", Name="ItemFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        WebClient.ItemService.Item[] latestAdded();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/latestAdded", ReplyAction="http://tempuri.org/IItemService/latestAddedResponse")]
        System.Threading.Tasks.Task<WebClient.ItemService.Item[]> latestAddedAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemRequest() {
        }
        
        public getItemRequest(int id, string message) {
            this.id = id;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Item getItemResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemResponse() {
        }
        
        public getItemResponse(WebClient.ItemService.Item getItemResult, string message) {
            this.getItemResult = getItemResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setItem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Person person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public setItemRequest() {
        }
        
        public setItemRequest(WebClient.ItemService.Person person, string message) {
            this.person = person;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setItemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool setItemResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public setItemResponse() {
        }
        
        public setItemResponse(bool setItemResult, string message) {
            this.setItemResult = setItemResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="itemsSold", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class itemsSoldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Person person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public itemsSoldRequest() {
        }
        
        public itemsSoldRequest(WebClient.ItemService.Person person, string message) {
            this.person = person;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="itemsSoldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class itemsSoldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Item[] itemsSoldResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public itemsSoldResponse() {
        }
        
        public itemsSoldResponse(WebClient.ItemService.Item[] itemsSoldResult, string message) {
            this.itemsSoldResult = itemsSoldResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemsCategory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemsCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemsCategoryRequest() {
        }
        
        public getItemsCategoryRequest(string category, string message) {
            this.category = category;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemsCategoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemsCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Item[] getItemsCategoryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemsCategoryResponse() {
        }
        
        public getItemsCategoryResponse(WebClient.ItemService.Item[] getItemsCategoryResult, string message) {
            this.getItemsCategoryResult = getItemsCategoryResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemsCart", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemsCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] idList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemsCartRequest() {
        }
        
        public getItemsCartRequest(int[] idList, string message) {
            this.idList = idList;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemsCartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getItemsCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Item[] getItemsCartResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getItemsCartResponse() {
        }
        
        public getItemsCartResponse(WebClient.ItemService.Item[] getItemsCartResult, string message) {
            this.getItemsCartResult = getItemsCartResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Person person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getOrdersRequest() {
        }
        
        public getOrdersRequest(WebClient.ItemService.Person person, string message) {
            this.person = person;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Order[] getOrdersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public getOrdersResponse() {
        }
        
        public getOrdersResponse(WebClient.ItemService.Order[] getOrdersResult, string message) {
            this.getOrdersResult = getOrdersResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Item[] orders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public setOrderRequest() {
        }
        
        public setOrderRequest(WebClient.ItemService.Item[] orders, string message) {
            this.orders = orders;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool setOrderResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public setOrderResponse() {
        }
        
        public setOrderResponse(bool setOrderResult, string message) {
            this.setOrderResult = setOrderResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bought", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class boughtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Person person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public boughtRequest() {
        }
        
        public boughtRequest(WebClient.ItemService.Person person, string message) {
            this.person = person;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="boughtResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class boughtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ItemService.Person person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public boughtResponse() {
        }
        
        public boughtResponse(WebClient.ItemService.Person person, string message) {
            this.person = person;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : WebClient.ItemService.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<WebClient.ItemService.IItemService>, WebClient.ItemService.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.getItemResponse WebClient.ItemService.IItemService.getItem(WebClient.ItemService.getItemRequest request) {
            return base.Channel.getItem(request);
        }
        
        public WebClient.ItemService.Item getItem(int id, ref string message) {
            WebClient.ItemService.getItemRequest inValue = new WebClient.ItemService.getItemRequest();
            inValue.id = id;
            inValue.message = message;
            WebClient.ItemService.getItemResponse retVal = ((WebClient.ItemService.IItemService)(this)).getItem(inValue);
            message = retVal.message;
            return retVal.getItemResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.getItemResponse> getItemAsync(WebClient.ItemService.getItemRequest request) {
            return base.Channel.getItemAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.setItemResponse WebClient.ItemService.IItemService.setItem(WebClient.ItemService.setItemRequest request) {
            return base.Channel.setItem(request);
        }
        
        public bool setItem(WebClient.ItemService.Person person, ref string message) {
            WebClient.ItemService.setItemRequest inValue = new WebClient.ItemService.setItemRequest();
            inValue.person = person;
            inValue.message = message;
            WebClient.ItemService.setItemResponse retVal = ((WebClient.ItemService.IItemService)(this)).setItem(inValue);
            message = retVal.message;
            return retVal.setItemResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.setItemResponse> setItemAsync(WebClient.ItemService.setItemRequest request) {
            return base.Channel.setItemAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.itemsSoldResponse WebClient.ItemService.IItemService.itemsSold(WebClient.ItemService.itemsSoldRequest request) {
            return base.Channel.itemsSold(request);
        }
        
        public WebClient.ItemService.Item[] itemsSold(WebClient.ItemService.Person person, ref string message) {
            WebClient.ItemService.itemsSoldRequest inValue = new WebClient.ItemService.itemsSoldRequest();
            inValue.person = person;
            inValue.message = message;
            WebClient.ItemService.itemsSoldResponse retVal = ((WebClient.ItemService.IItemService)(this)).itemsSold(inValue);
            message = retVal.message;
            return retVal.itemsSoldResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.itemsSoldResponse> itemsSoldAsync(WebClient.ItemService.itemsSoldRequest request) {
            return base.Channel.itemsSoldAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.getItemsCategoryResponse WebClient.ItemService.IItemService.getItemsCategory(WebClient.ItemService.getItemsCategoryRequest request) {
            return base.Channel.getItemsCategory(request);
        }
        
        public WebClient.ItemService.Item[] getItemsCategory(string category, ref string message) {
            WebClient.ItemService.getItemsCategoryRequest inValue = new WebClient.ItemService.getItemsCategoryRequest();
            inValue.category = category;
            inValue.message = message;
            WebClient.ItemService.getItemsCategoryResponse retVal = ((WebClient.ItemService.IItemService)(this)).getItemsCategory(inValue);
            message = retVal.message;
            return retVal.getItemsCategoryResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.getItemsCategoryResponse> getItemsCategoryAsync(WebClient.ItemService.getItemsCategoryRequest request) {
            return base.Channel.getItemsCategoryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.getItemsCartResponse WebClient.ItemService.IItemService.getItemsCart(WebClient.ItemService.getItemsCartRequest request) {
            return base.Channel.getItemsCart(request);
        }
        
        public WebClient.ItemService.Item[] getItemsCart(int[] idList, ref string message) {
            WebClient.ItemService.getItemsCartRequest inValue = new WebClient.ItemService.getItemsCartRequest();
            inValue.idList = idList;
            inValue.message = message;
            WebClient.ItemService.getItemsCartResponse retVal = ((WebClient.ItemService.IItemService)(this)).getItemsCart(inValue);
            message = retVal.message;
            return retVal.getItemsCartResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.getItemsCartResponse> getItemsCartAsync(WebClient.ItemService.getItemsCartRequest request) {
            return base.Channel.getItemsCartAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.getOrdersResponse WebClient.ItemService.IItemService.getOrders(WebClient.ItemService.getOrdersRequest request) {
            return base.Channel.getOrders(request);
        }
        
        public WebClient.ItemService.Order[] getOrders(WebClient.ItemService.Person person, ref string message) {
            WebClient.ItemService.getOrdersRequest inValue = new WebClient.ItemService.getOrdersRequest();
            inValue.person = person;
            inValue.message = message;
            WebClient.ItemService.getOrdersResponse retVal = ((WebClient.ItemService.IItemService)(this)).getOrders(inValue);
            message = retVal.message;
            return retVal.getOrdersResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.getOrdersResponse> getOrdersAsync(WebClient.ItemService.getOrdersRequest request) {
            return base.Channel.getOrdersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.setOrderResponse WebClient.ItemService.IItemService.setOrder(WebClient.ItemService.setOrderRequest request) {
            return base.Channel.setOrder(request);
        }
        
        public bool setOrder(WebClient.ItemService.Item[] orders, ref string message) {
            WebClient.ItemService.setOrderRequest inValue = new WebClient.ItemService.setOrderRequest();
            inValue.orders = orders;
            inValue.message = message;
            WebClient.ItemService.setOrderResponse retVal = ((WebClient.ItemService.IItemService)(this)).setOrder(inValue);
            message = retVal.message;
            return retVal.setOrderResult;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.setOrderResponse> setOrderAsync(WebClient.ItemService.setOrderRequest request) {
            return base.Channel.setOrderAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ItemService.boughtResponse WebClient.ItemService.IItemService.bought(WebClient.ItemService.boughtRequest request) {
            return base.Channel.bought(request);
        }
        
        public void bought(ref WebClient.ItemService.Person person, ref string message) {
            WebClient.ItemService.boughtRequest inValue = new WebClient.ItemService.boughtRequest();
            inValue.person = person;
            inValue.message = message;
            WebClient.ItemService.boughtResponse retVal = ((WebClient.ItemService.IItemService)(this)).bought(inValue);
            person = retVal.person;
            message = retVal.message;
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.boughtResponse> boughtAsync(WebClient.ItemService.boughtRequest request) {
            return base.Channel.boughtAsync(request);
        }
        
        public WebClient.ItemService.Item[] latestAdded() {
            return base.Channel.latestAdded();
        }
        
        public System.Threading.Tasks.Task<WebClient.ItemService.Item[]> latestAddedAsync() {
            return base.Channel.latestAddedAsync();
        }
    }
}
