//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public int itemId { get; set; }
        public int personId { get; set; }
        public string comment1 { get; set; }
        public System.DateTime commentDay { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Person Person { get; set; }
    }
}
