//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int personId { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string description { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
